site_name: Nember API Docs
site_url: https://mydomain.org/mysite
theme:
  name: material
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
